### ISSUE TITLE
Eureka-server running error

### ISSUE THREAD

**Issue by Hamdam23** [Hamdam23/courseland#1]
An error occurred after playing with the pom.xml(courseland), and pom.xml(eureka-server) dependencies. The current version is pushed to the [lower branch](https://github.com/Hamdam23/courseland/tree/lower)!

![image](https://user-images.githubusercontent.com/90045606/223727418-1fc714d3-5215-4115-9c49-94f7e97d59f5.png)

**Comment by KhusainovFarrukh** [comment]
In parent pom.xml:
1. Change `spring.boot.maven.plugin.version` and `spring.boot.dependencies.version` to `2.7.8`
2. Change `spring.cloud-version` to the version which is compatible with Spring Boot 2.7.8 (for example 2021.0.3)

Learn more about the Spring Cloud Release train compatibility, you can visit [this page](https://spring.io/projects/spring-cloud#overview) and check the **Release Trains** section.
If you want to disable version compatibility check, just set the property `spring.cloud.compatibility-verifier.enabled=false`

**Comment by KhusainovFarrukh** [comment]
> If you an existing Spring Boot app you want to add Spring Cloud to that app, **the first step** is to determine the version of Spring Cloud you should use. The version you use in your app will depend on the version of Spring Boot you are using.

**Comment by Hamdam23** [comment]
It worked, appreciate your help!
